# Generated by Django 5.1.1 on 2024-10-03 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sensors", "0002_datacollection_solenoidstate_delete_sensordata_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="datacollection",
            name="solenoid_state",
        ),
    ]
