# Generated by Django 5.1.1 on 2024-10-03 00:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensors", "0003_remove_datacollection_solenoid_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="datacollection",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
