# Generated by Django 5.1.1 on 2024-10-04 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensors", "0004_datacollection_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="solenoidstate",
            name="flow_rate",
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name="solenoidstate",
            name="water_used",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
