# Generated by Django 5.1.1 on 2024-10-04 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensors", "0005_solenoidstate_flow_rate_solenoidstate_water_used"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlowRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rate", models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name="solenoidstate",
            name="flow_rate",
        ),
    ]
