# Generated by Django 5.1.1 on 2024-10-04 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensors", "0006_flowrate_remove_solenoidstate_flow_rate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="solenoidstate",
            name="water_used",
        ),
        migrations.CreateModel(
            name="WaterUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("water_used", models.FloatField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "solenoid_state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="water_usages",
                        to="sensors.solenoidstate",
                    ),
                ),
            ],
        ),
    ]
