# Generated by Django 5.1.1 on 2024-10-17 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensors", "0008_configuracao"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataFertil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("interval_hours", models.PositiveIntegerField(default=24)),
                ("last_fertil", models.DateTimeField(blank=True, null=True)),
                ("start_feril", models.BooleanField(default=False)),
            ],
        ),
    ]
