# Generated by Django 5.1.1 on 2024-10-17 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensors", "0009_datafertil"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="datafertil",
            name="last_fertil",
        ),
        migrations.CreateModel(
            name="HistoricoFertil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_irrigacao", models.DateTimeField(auto_now_add=True)),
                (
                    "data_fertil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sensors.datafertil",
                    ),
                ),
            ],
        ),
    ]
