# Generated by Django 5.1.1 on 2024-10-17 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sensors", "0010_remove_datafertil_last_fertil_historicofertil"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicofertil",
            old_name="data_irrigacao",
            new_name="data_fertil_irrigacao",
        ),
        migrations.RemoveField(
            model_name="historicofertil",
            name="data_fertil",
        ),
    ]
