# Generated by Django 5.1.1 on 2024-10-17 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "sensors",
            "0011_rename_data_irrigacao_historicofertil_data_fertil_irrigacao_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="historicofertil",
            name="data_fertil",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="historicofertil_set",
                to="sensors.datafertil",
            ),
            preserve_default=False,
        ),
    ]
