# Generated by Django 5.1.1 on 2024-10-17 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensors", "0012_historicofertil_data_fertil"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="datafertil",
            name="interval_hours",
        ),
        migrations.AddField(
            model_name="datafertil",
            name="interval_minutes",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
