# Generated by Django 5.1.1 on 2024-10-17 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sensors", "0013_remove_datafertil_interval_hours_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="datafertil",
            name="start_feril",
        ),
    ]
