# Generated by Django 5.1.1 on 2024-10-17 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensors", "0015_datafertil_start_fertil"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicofertil",
            name="data_fertil",
        ),
        migrations.AlterField(
            model_name="datafertil",
            name="start_fertil",
            field=models.BooleanField(),
        ),
    ]
