# Generated by Django 5.1.1 on 2024-10-17 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensors", "0016_remove_historicofertil_data_fertil_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfigFertil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_fertil", models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="StatusFertil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_fertil", models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameModel(
            old_name="HistoricoFertil",
            new_name="StoricFertil",
        ),
        migrations.DeleteModel(
            name="DataFertil",
        ),
    ]
