# Generated by Django 5.1.1 on 2024-10-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensors", "0017_configfertil_statusfertil_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="statusfertil",
            name="tempo_ligacao",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
